[package]
name = "turbolint_cli"
version.workspace = true
edition = "2021"

[[bin]]
name = "turbolint"
path = "src/main.rs"

[dependencies]
turbolint_core = { path = "../turbolint_core" }
turbolint_config = { path = "../turbolint_config" }
turbolint_rules = { path = "../turbolint_rules" }
clap = { workspace = true }
miette = { workspace = true }
glob = { workspace = true }
rayon = { workspace = true }
colored = { workspace = true }
